### ISSUE TITLE
What's the best way to add the current request object to Jinja's globals?

### ISSUE THREAD

**Issue by Deimos** [Pylons/pyramid_jinja2#155]
When importing macros in Jinja, [they only have access to the globals by default](https://jinja.palletsprojects.com/en/2.11.x/templates/#import). Quite a few of my macros need to use `request` for things like permission checks (via `.has_permission()`), so those macros always need to be imported using `with context` so that they can use the request object, otherwise it's only accessible in the "top-level" template.

I'd like to try and improve this by adding `request` to the Jinja globals so that macros can always access it, but I'm having trouble figuring out a way to do it.

For example, even though it was probably a terrible idea, I tried adding `pyramid.threadlocal.get_current_request()` to the globals, but that doesn't seem to work correctly.

Any recommendations for a good way (or any way) to accomplish this?

**Comment by mmerickel** [comment]
`with context` is the approach that I use, or just passing the request into the macro as an argument. You could make an object proxy that invokes `get_current_request()` under the hood but I'm not sure I'd recommend it. What I mean by that is a class that overrides `__getattribute__` and forwards everything into the result of `get_current_request()`.

It's not available in the other files, I'm pretty sure, because jinja2 caches the other files separately, so they are not recompiled for each template they are used within and thus don't have access to the context in the caller's template without `with context`.

Anyway I don't think this issue will result in any changes to pyramid_jinja2 so I'm gonna close it. If you want more usage advice I'd point you at the mailing list.

**Comment by mmerickel** [comment]
> For example, even though it was probably a terrible idea, I tried adding pyramid.threadlocal.get_current_request() to the globals, but that doesn't seem to work correctly.

To be clear, the issue with this approach is you're invoking `get_current_request()` at config-time when there is no request, so it returns None and binds that value to your global.

You'd need to instead inject `jinja2.globals = {'get_current_request': pyramid.threadlocal.get_current_request}` and then in your macro templates you could use `{{ get_current_request().has_permission('foo') }}`.

**Comment by Deimos** [comment]
Thanks for such a quick response - if there's no straightforward way to do it, I'll probably just stick to `with context` since that's really only a minor inconvenience and is probably safest anyway, to avoid running into surprising issues with Jinja's import-caching.

I appreciate the advice, thanks again!
